import Head from 'next/head'
import Image from 'next/image'
import styles from './starting-page.module.css'
import NewsList from '../news/NewsList'

const StartingPage = (props) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Union</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewsList newsData={props.news} className={styles.card} />
      <footer className={styles.footer}>

        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/sditdevalt.svg" alt="SdItDev Logo" width={72} height={50} />
        </span>

      </footer>
    </div >
  )
};

export default StartingPage;