import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Union</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/profile" className={styles.card}>
            <h2>Profil &rarr;</h2>
            <p>Sve informacije vezane za korisnika kao i licna podesavanja</p>
          </Link>
          <Link href="/auth" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Napravite novi nalog ili se ulogujte</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://next-js-finalatlas.vercel.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/sditdevalt.svg" alt="SdItDev Logo" width={72} height={50} />
          </span>
        </a>
      </footer>
    </div>
  )
}
